### ISSUE TITLE
Updating Probot

### ISSUE THREAD

**Issue by hiimbex** [behaviorbot/welcome#15]
Probot is currently on [v7.2.0](https://github.com/probot/probot/releases/tag/v7.2.0), while several behavior bot apps are lagging behind. I'd appreciate some help getting them all updated!

This will require the following:
1. updating the `Probot` entry in each [package.json](https://github.com/behaviorbot/update-docs/blob/master/package.json).
1. Running `npm install` (If you don't already have node and npm installed, you'll need to do so [here](https://nodejs.org/en/download/)).
1. Running `npm test` and fixing any errors that may arise from that. I think the main issue will be renaming `robot` to `app`.
1. Get all tests back to passing;
1. Open a PR and ping me for review!

Here are the apps that need updating:
- [x] [sentiment-bot](https://github.com/behaviorbot/sentiment-bot)
- [x] [request-info](https://github.com/behaviorbot/request-info)
- [ ] [welcome](https://github.com/behaviorbot/welcome) (Welcome depends on these 3 sub-apps which will need to be updated first:
  - [x] [first-pr-merge](https://github.com/behaviorbot/first-pr-merge)
  - [x] [new-pr-welcome](https://github.com/behaviorbot/new-pr-welcome)
  - [x] [new-issue-welcome](https://github.com/behaviorbot/new-issue-welcome)
- [x] [update-docs](https://github.com/behaviorbot/update-docs)

**Comment by LakshSingla** [comment]
Hello, can I start working on this issue ?

**Comment by MikaelSmith** [comment]
Looks like welcome didn't get updated based on this. Probot's also up to 9.3.0. I'll see what I can do about it.

**Comment by lucasvazq** [comment]
Then, can close this issue?
