### ISSUE TITLE
Error: Empty value for parameter 'body': undefined

### ISSUE THREAD

**Issue by bkeepers** [behaviorbot/welcome#4]
https://sentry.io/probot/welcome/issues/323440102/

```
Error: Empty value for parameter 'body': undefined
```

It looks like this happens when a `.github/config.yml` exists, but doesn't have the property that the plugins expects.

**Comment by hiimbex** [comment]
Solved through:
- behaviorbot/first-pr-merge#13
- behaviorbot/new-issue-welcome#26
- behaviorbot/new-pr-welcome#9

Thanks!
