### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by Mte90** [behaviorbot/welcome#9]
I am using that bot on organization and I want to avoid to add a config file in all the repo.
It will be helpful to have a way to set an unique file for all the repo of an organization that shares the settings.

**Comment by hiimbex** [comment]
Yea this is something the maintainers of [probot](https://github.com/probot/probot), (the platform on which the behaviorbot apps are built on) have discussed a few times. Right now there's no easy way to do it. A few people have written scripts to automate adding the config files to their orgs (@benbalter  https://github.com/benbalter/probot-shared-config).

If we were to add this feature how would you want it to work? 

Cc/ @bkeepers

**Comment by Mte90** [comment]
Uhm probably something that you can configure on probot when you activate will be the best solution.
Maybe create a single repo on the user that installed the bot will be a way. Inside a config file with all the settings for the projects or organization.

**Comment by hiimbex** [comment]
I'm +1 for this, but it would definitely get built into the probot core. So I'm gonna close this out, but you can follow along our progress in https://github.com/probot/probot/issues/258
